"""add_read_at_to_classifications

Revision ID: 1b90459b016f
Revises: 4d07a17040aa
Create Date: 2026-07-02 09:12:00.762752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b90459b016f'
down_revision: Union[str, Sequence[str], None] = '4d07a17040aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'read_at')
    # ### end Alembic commands ###
