"""initial

Revision ID: 4d07a17040aa
Revises: 
Create Date: 2026-07-01 20:06:20.704298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d07a17040aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('refnr', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('firma', sa.String(), nullable=False),
    sa.Column('externe_url', sa.String(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('ort_raw', sa.String(), nullable=False),
    sa.Column('vollzeit', sa.Boolean(), nullable=False),
    sa.Column('ats_source', sa.String(), nullable=False),
    sa.Column('ats_slug', sa.String(), nullable=False),
    sa.Column('via', sa.String(), nullable=True),
    sa.Column('salary_min_raw', sa.Float(), nullable=True),
    sa.Column('salary_max_raw', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('salary_summary', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('refnr')
    )
    op.create_index(op.f('ix_jobs_role'), 'jobs', ['role'], unique=False)
    op.create_table('classifications',
    sa.Column('refnr', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('company_stage', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('titel', sa.String(), nullable=True),
    sa.Column('ort', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('english_ok', sa.Boolean(), nullable=False),
    sa.Column('german_level', sa.String(), nullable=True),
    sa.Column('on_call', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('certifications_required', sa.String(), nullable=True),
    sa.Column('education_required', sa.String(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['refnr'], ['jobs.refnr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refnr')
    )
    op.create_index(op.f('ix_classifications_role'), 'classifications', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_role'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_jobs_role'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
